### ISSUE TITLE
Support JSON requests for updates

### ISSUE THREAD

**Issue by thomascorthals** [solariumphp/solarium#1004]
As discussed in issue #992 / PR #994, JSON updates are necessary to index single nested child documents. They also open up atomic update functionality for nested documents that isn't available through XML.

This is how I would break down the work.

- [x] #994 moves XML specific character filtering from `Update\Query\Document` to `Update\RequestBuilder`
- [x] #1011 implements Solr-Style JSON representation of `Update\Query\Document`
- [x] #1030 makes `RequestBuilder`s responsible for setting the `Content-Type`
- [x] #1033 introduces the JSON version of `Update\RequestBuilder`
- [x] #1037 adds JSON requests to `BufferedAdd`/`BufferedDelete`
- [x] #1038 adds integration tests for JSON to ensure functional equivalence with XML
- [x] Decide whether/when to make JSON updates the default behaviour
- [ ] #1044 updates documentation on nested documents, boosts and how to choose between XML and JSON if it does matter for your use case

Did I miss anything?

**Comment by thomascorthals** [comment]
The Solr-Style JSON representation of documents is done in my fork: https://github.com/thomascorthals/solarium/tree/json. Can't open a PR yet because it needs #994 merged to pass the unit tests for the representation of child documents.

**Comment by thomascorthals** [comment]
Something for the documentation: `setInputEncoding()` will probably result in errors for JSON requests.

https://www.rfc-editor.org/rfc/rfc8259#section-8.1

> JSON text exchanged between systems that are not part of a closed ecosystem MUST be encoded using UTF-8 [[RFC3629](https://www.rfc-editor.org/rfc/rfc3629)].

Or is that worthy of actually throwing a RuntimeException for? Solr errors are rather cryptical if you don't have a clue what's going on:

```json
{
  "responseHeader":{
    "status":400,
    "QTime":0},
  "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.solr.common.SolrException"],
    "msg":"Expected: OBJECT_START but got STRING at [9]",
    "code":400}}
```

**Comment by mkalkbrenner** [comment]
great progress, thank you!

**Comment by thomascorthals** [comment]
@mkalkbrenner I think we should decide whether we'll make JSON requests the default behaviour at some point before I update the documentation. Then I can include something like "this will become the default behaviour in a future release" (or maybe even which release?) and encourage users to test it already so they aren't caught unaware.

If no "unfixable" bugs surface, I don't see a reason not to make this the default. Performance is better, nested document support is better. Index time boosts aren't supported, but those are deprecated in Solr anyway.

**Comment by mkalkbrenner** [comment]
I agree to use JSON as default.
